name: exploress
description: Exploress, marketing and exploration app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.23+1
developer: Hassan Kajila,

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  package_info: ^2.0.0
  intl: ^0.17.0

  equatable: ^2.0.0
  pedantic: ^1.11.0
  formz: ^0.4.0
  #flutter_bloc: ^7.0.1

  #permission_handler: ^6.1.1

  #url_launcher: ^6.0.3
  google_maps_flutter: ^2.0.2
  #latlong: ^0.6.1
  latlong2: ^0.8.0
  #location: ^4.1.1
  geolocator: ^7.0.1
  http: ^0.13.1
  json_serializable: ^4.1.0


  objectbox_flutter_libs: ^0.14.0
  objectbox: ^0.14.0
  path_provider: ^2.0.1

  hive: ^2.0.4
  hive_flutter: ^1.0.0

  #cloud_functions: ^0.6.0+1
  #firebase_storage: ^4.0.1
  #firebase_storage: ^8.1.3
  #cloud_firestore: ^2.2.2
  firebase_core: ^1.7.0
  #firebase_database: ^7.1.1
  #firebase_auth: ^1.4.1
  #flutter_facebook_auth: ^3.3.0+2
  #google_sign_in: ^5.0.0

  #local_auth: ^0.4.0+1
  #path: ^1.7.0
  #cached_network_image: ^2.5.0

  animations: ^2.0.0
  animate_icons: ^2.0.0
  #google_fonts: ^1.1.0
  font_awesome_flutter: ^9.0.0
  #smooth_star_rating: ^1.1.1
  cupertino_icons: ^0.1.3
  awesome_dialog: ^2.1.0
  shimmer: ^2.0.0
  flutter_markdown: ^0.6.2
  share_plus: ^2.1.4
  #achievement_view: ^0.2.1

  permission_handler: ^8.1.6

  exploress_repository:
    path: ../packages/exploress_packages
  utils_component:
    git:
      url: https://github.com/lordyhas/utils_component

  #exploress_repository:
    #git:
      #url: https://github.com/lordyhas/exploress_packages



#  Run build task -> flutter pub run build_runner build
#To generate ObjectBox binding code for your entities run -> flutter pub run build_runner build
dev_dependencies:

  build_runner: ^2.0.6
  #objectbox_generator: ^0.14.0
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter

  #flutter_lints: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/img/background/
    - assets/img/shop_image/
 #   - assets/vectors/
 #   - assets/img/vector/
    - assets/img/pub_sofa.jpeg
    - assets/img/pub_headset.jpeg
    - assets/img/background/banner_bg.png


  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          style: italic
